# Generated by Django 6.0.2 on 2026-02-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('peso_kg', models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=5)),
                ('estatura_cm', models.IntegerField(help_text='Estatura en centímetros')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstudioRadiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estudio', models.CharField(choices=[('RX_TORAX', 'Rayos X de Tórax'), ('RX_OSEO', 'Rayos X Óseo'), ('TAC', 'Tomografía Axial Computarizada'), ('RM', 'Resonancia Magnética'), ('USG', 'Ultrasonido')], max_length=50)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de realizar'), ('REALIZADO', 'Imágenes capturadas'), ('DICTAMINADO', 'Diagnosticado por Radiólogo')], default='PENDIENTE', max_length=20)),
                ('diagnostico_clinico', models.TextField(blank=True, null=True)),
                ('radiologo_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_radiologo', to=settings.AUTH_USER_MODEL)),
                ('tecnico_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_tecnico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='clinica.paciente')),
            ],
        ),
    ]
