# Generated by Django 6.0.2 on 2026-05-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='comentarios',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estatus',
            field=models.CharField(blank=True, default='En espera', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hora_estudio',
            field=models.CharField(blank=True, default='Por definir', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_estudio',
            field=models.CharField(blank=True, default='Rayos X', max_length=100, null=True),
        ),
    ]
